In [5]:
import pandas as pd

In [8]:
delivery_data = pd.read_csv('datasets/delivery_data.csv', encoding='utf-8')

In [9]:
delivery_data

,datetime,Day of the week,city,population,hour,rain,dust,humidity,precipitation,temp,windspeed,holiday,sectors
0,2020-01-01,Wednesday,41281,467673,0,0,NaN,75,0.0,-2.7,0.9,1,6
1,2020-01-01,Wednesday,41281,467673,1,0,NaN,67,0.0,-1.8,1.2,1,6
2,2020-01-01,Wednesday,41281,467673,11,0,NaN,72,0.0,0.6,1.0,1,1
3,2020-01-01,Wednesday,41281,467673,12,0,NaN,74,0.0,0.2,0.7,1,1
4,2020-01-01,Wednesday,41281,467673,13,0,NaN,73,0.0,0.0,0.9,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
100212,2020-06-14,Sunday,11290,441812,19,0,37.0,81,0.0,18.7,1.0,0,3
100213,2020-06-19,Friday,11290,441812,11,0,25.0,62,0.0,24.2,2.6,0,3
100214,2020-06-20,Saturday,11290,441812,21,0,39.0,65,0.0,22.8,1.3,0,3
100215,2020-06-25,Thursday,11290,441812,11,1,15.0,88,0.0,20.6,1.5,0,3
100216,2020-06-25,Thursday,11290,441812,13,0,15.0,90,0.5,20.3,1.3,0,3